from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 645)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Sn = QtWidgets.QLineEdit(self.centralwidget)
        self.Sn.setGeometry(QtCore.QRect(60, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Sn.setFont(font)
        self.Sn.setMaxLength(20)
        self.Sn.setObjectName("Sn")
        self.Sb = QtWidgets.QLineEdit(self.centralwidget)
        self.Sb.setGeometry(QtCore.QRect(60, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Sb.setFont(font)
        self.Sb.setMaxLength(20)
        self.Sb.setObjectName("Sb")
        self.Ub = QtWidgets.QLineEdit(self.centralwidget)
        self.Ub.setGeometry(QtCore.QRect(60, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Ub.setFont(font)
        self.Ub.setMaxLength(20)
        self.Ub.setObjectName("Ub")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.Xd = QtWidgets.QLineEdit(self.centralwidget)
        self.Xd.setGeometry(QtCore.QRect(60, 210, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Xd.setFont(font)
        self.Xd.setMaxLength(10)
        self.Xd.setObjectName("Xd")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 260, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 310, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 360, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 460, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.Xq = QtWidgets.QLineEdit(self.centralwidget)
        self.Xq.setGeometry(QtCore.QRect(60, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Xq.setFont(font)
        self.Xq.setMaxLength(10)
        self.Xq.setObjectName("Xq")
        self.Xd1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Xd1.setGeometry(QtCore.QRect(60, 310, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Xd1.setFont(font)
        self.Xd1.setMaxLength(10)
        self.Xd1.setObjectName("Xd1")
        self.Xq1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Xq1.setGeometry(QtCore.QRect(60, 360, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Xq1.setFont(font)
        self.Xq1.setMaxLength(10)
        self.Xq1.setObjectName("Xq1")
        self.Xd2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Xd2.setGeometry(QtCore.QRect(60, 410, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Xd2.setFont(font)
        self.Xd2.setMaxLength(10)
        self.Xd2.setObjectName("Xd2")
        self.Xq2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Xq2.setGeometry(QtCore.QRect(60, 460, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Xq2.setFont(font)
        self.Xq2.setMaxLength(10)
        self.Xq2.setObjectName("Xq2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(330, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(310, 20, 20, 571))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(330, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.calculate = QtWidgets.QPushButton(self.centralwidget)
        self.calculate.setGeometry(QtCore.QRect(914, 550, 93, 28))
        self.calculate.setObjectName("calculate")
        self.S2 = QtWidgets.QLineEdit(self.centralwidget)
        self.S2.setGeometry(QtCore.QRect(60, 510, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.S2.setFont(font)
        self.S2.setMaxLength(20)
        self.S2.setObjectName("S2")
        self.Ib = QtWidgets.QLineEdit(self.centralwidget)
        self.Ib.setGeometry(QtCore.QRect(370, 160, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Ib.setFont(font)
        self.Ib.setMaxLength(40)
        self.Ib.setObjectName("Ib")
        self.Zb = QtWidgets.QLineEdit(self.centralwidget)
        self.Zb.setGeometry(QtCore.QRect(370, 110, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Zb.setFont(font)
        self.Zb.setMaxLength(40)
        self.Zb.setObjectName("Zb")
        self.comboUb = QtWidgets.QComboBox(self.centralwidget)
        self.comboUb.setGeometry(QtCore.QRect(220, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboUb.setFont(font)
        self.comboUb.setObjectName("comboUb")
        self.comboUb.addItem("")
        self.comboUb.addItem("")
        self.comboUb.addItem("")
        self.comboSb = QtWidgets.QComboBox(self.centralwidget)
        self.comboSb.setGeometry(QtCore.QRect(220, 110, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboSb.setFont(font)
        self.comboSb.setObjectName("comboSb")
        self.comboSb.addItem("")
        self.comboSb.addItem("")
        self.comboSb.addItem("")
        self.comboSb.addItem("")
        self.comboSn = QtWidgets.QComboBox(self.centralwidget)
        self.comboSn.setGeometry(QtCore.QRect(220, 60, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboSn.setFont(font)
        self.comboSn.setObjectName("comboSn")
        self.comboSn.addItem("")
        self.comboSn.addItem("")
        self.comboSn.addItem("")
        self.comboSn.addItem("")
        self.comboS2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboS2.setGeometry(QtCore.QRect(230, 510, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comboS2.setFont(font)
        self.comboS2.setObjectName("comboS2")
        self.comboS2.addItem("")
        self.comboS2.addItem("")
        self.comboS2.addItem("")
        self.comboS2.addItem("")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(330, 310, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(330, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(320, 350, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(320, 210, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(330, 450, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(320, 260, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_22.setObjectName("label_22")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(620, 100, 20, 491))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Ug = QtWidgets.QLineEdit(self.centralwidget)
        self.Ug.setGeometry(QtCore.QRect(370, 60, 471, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Ug.setFont(font)
        self.Ug.setMaxLength(50)
        self.Ug.setReadOnly(False)
        self.Ug.setObjectName("Ug")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(330, 60, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(330, 510, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(640, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(640, 110, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(640, 200, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(640, 250, 31, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(640, 310, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(640, 360, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_30.setFont(font)
        self.label_30.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.centralwidget)
        self.label_31.setGeometry(QtCore.QRect(640, 410, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_31.setFont(font)
        self.label_31.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.centralwidget)
        self.label_32.setGeometry(QtCore.QRect(640, 460, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.centralwidget)
        self.label_33.setGeometry(QtCore.QRect(900, 60, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_33.setFont(font)
        self.label_33.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.centralwidget)
        self.label_34.setGeometry(QtCore.QRect(900, 110, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.centralwidget)
        self.label_35.setGeometry(QtCore.QRect(900, 210, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.centralwidget)
        self.label_36.setGeometry(QtCore.QRect(900, 160, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.centralwidget)
        self.label_37.setGeometry(QtCore.QRect(900, 310, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.centralwidget)
        self.label_38.setGeometry(QtCore.QRect(900, 260, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_38.setObjectName("label_38")
        self.S2pu = QtWidgets.QLineEdit(self.centralwidget)
        self.S2pu.setGeometry(QtCore.QRect(370, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.S2pu.setFont(font)
        self.S2pu.setMaxLength(50)
        self.S2pu.setObjectName("S2pu")
        self.Ugpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Ugpu.setGeometry(QtCore.QRect(370, 260, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Ugpu.setFont(font)
        self.Ugpu.setMaxLength(50)
        self.Ugpu.setObjectName("Ugpu")
        self.deltaIgpu = QtWidgets.QLineEdit(self.centralwidget)
        self.deltaIgpu.setGeometry(QtCore.QRect(370, 360, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.deltaIgpu.setFont(font)
        self.deltaIgpu.setMaxLength(50)
        self.deltaIgpu.setObjectName("deltaIgpu")
        self.Igpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Igpu.setGeometry(QtCore.QRect(370, 310, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Igpu.setFont(font)
        self.Igpu.setMaxLength(50)
        self.Igpu.setObjectName("Igpu")
        self.EQ = QtWidgets.QLineEdit(self.centralwidget)
        self.EQ.setGeometry(QtCore.QRect(370, 410, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.EQ.setFont(font)
        self.EQ.setMaxLength(40)
        self.EQ.setObjectName("EQ")
        self.phi = QtWidgets.QLineEdit(self.centralwidget)
        self.phi.setGeometry(QtCore.QRect(370, 460, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.phi.setFont(font)
        self.phi.setMaxLength(40)
        self.phi.setObjectName("phi")
        self.BC = QtWidgets.QLineEdit(self.centralwidget)
        self.BC.setGeometry(QtCore.QRect(370, 510, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.BC.setFont(font)
        self.BC.setMaxLength(40)
        self.BC.setObjectName("BC")
        self.AB = QtWidgets.QLineEdit(self.centralwidget)
        self.AB.setGeometry(QtCore.QRect(690, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.AB.setFont(font)
        self.AB.setMaxLength(20)
        self.AB.setObjectName("AB")
        self.gamma = QtWidgets.QLineEdit(self.centralwidget)
        self.gamma.setGeometry(QtCore.QRect(690, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gamma.setFont(font)
        self.gamma.setMaxLength(20)
        self.gamma.setObjectName("gamma")
        self.Udpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Udpu.setGeometry(QtCore.QRect(690, 460, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Udpu.setFont(font)
        self.Udpu.setMaxLength(20)
        self.Udpu.setObjectName("Udpu")
        self.alfa = QtWidgets.QLineEdit(self.centralwidget)
        self.alfa.setGeometry(QtCore.QRect(690, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.alfa.setFont(font)
        self.alfa.setMaxLength(20)
        self.alfa.setObjectName("alfa")
        self.Uqpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Uqpu.setGeometry(QtCore.QRect(690, 410, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Uqpu.setFont(font)
        self.Uqpu.setMaxLength(20)
        self.Uqpu.setObjectName("Uqpu")
        self.OA = QtWidgets.QLineEdit(self.centralwidget)
        self.OA.setGeometry(QtCore.QRect(690, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.OA.setFont(font)
        self.OA.setMaxLength(20)
        self.OA.setObjectName("OA")
        self.Iqpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Iqpu.setGeometry(QtCore.QRect(690, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Iqpu.setFont(font)
        self.Iqpu.setMaxLength(20)
        self.Iqpu.setObjectName("Iqpu")
        self.Idpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Idpu.setGeometry(QtCore.QRect(690, 360, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Idpu.setFont(font)
        self.Idpu.setMaxLength(20)
        self.Idpu.setObjectName("Idpu")
        self.Eqpu2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Eqpu2.setGeometry(QtCore.QRect(960, 110, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Eqpu2.setFont(font)
        self.Eqpu2.setMaxLength(20)
        self.Eqpu2.setObjectName("Eqpu2")
        self.Eqpu1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Eqpu1.setGeometry(QtCore.QRect(960, 210, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Eqpu1.setFont(font)
        self.Eqpu1.setMaxLength(20)
        self.Eqpu1.setObjectName("Eqpu1")
        self.Edpu1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Edpu1.setGeometry(QtCore.QRect(960, 160, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Edpu1.setFont(font)
        self.Edpu1.setMaxLength(20)
        self.Edpu1.setObjectName("Edpu1")
        self.Edpu2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Edpu2.setGeometry(QtCore.QRect(960, 60, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Edpu2.setFont(font)
        self.Edpu2.setMaxLength(20)
        self.Edpu2.setObjectName("Edpu2")
        self.Edpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Edpu.setGeometry(QtCore.QRect(960, 260, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Edpu.setFont(font)
        self.Edpu.setMaxLength(20)
        self.Edpu.setObjectName("Edpu")
        self.Eqpu = QtWidgets.QLineEdit(self.centralwidget)
        self.Eqpu.setGeometry(QtCore.QRect(960, 310, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Eqpu.setFont(font)
        self.Eqpu.setMaxLength(20)
        self.Eqpu.setObjectName("Eqpu")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        self.label_39.setGeometry(QtCore.QRect(900, 460, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_39.setFont(font)
        self.label_39.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.centralwidget)
        self.label_40.setGeometry(QtCore.QRect(900, 410, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_40.setFont(font)
        self.label_40.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.centralwidget)
        self.label_41.setGeometry(QtCore.QRect(900, 360, 51, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_41.setFont(font)
        self.label_41.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_41.setObjectName("label_41")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(920, 500, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_20.setObjectName("label_20")
        self.Epu1 = QtWidgets.QLineEdit(self.centralwidget)
        self.Epu1.setGeometry(QtCore.QRect(960, 410, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Epu1.setFont(font)
        self.Epu1.setMaxLength(20)
        self.Epu1.setObjectName("Epu1")
        self.Epu = QtWidgets.QLineEdit(self.centralwidget)
        self.Epu.setGeometry(QtCore.QRect(960, 360, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Epu.setFont(font)
        self.Epu.setMaxLength(20)
        self.Epu.setObjectName("Epu")
        self.Epu2 = QtWidgets.QLineEdit(self.centralwidget)
        self.Epu2.setGeometry(QtCore.QRect(960, 460, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.Epu2.setFont(font)
        self.Epu2.setMaxLength(20)
        self.Epu2.setObjectName("Epu2")
        self.delta = QtWidgets.QLineEdit(self.centralwidget)
        self.delta.setGeometry(QtCore.QRect(960, 510, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.delta.setFont(font)
        self.delta.setMaxLength(20)
        self.delta.setObjectName("delta")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(870, 20, 20, 521))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.help = QtWidgets.QPushButton(self.centralwidget)
        self.help.setEnabled(True)
        self.help.setGeometry(QtCore.QRect(220, 10, 81, 31))
        self.help.setAutoFillBackground(False)
        self.help.setStyleSheet("")
        self.help.setIconSize(QtCore.QSize(40, 40))
        self.help.setDefault(False)
        self.help.setFlat(False)
        self.help.setObjectName("help")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(1020, 550, 93, 28))
        self.save.setObjectName("save")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(160, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(160, 260, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_42 = QtWidgets.QLabel(self.centralwidget)
        self.label_42.setGeometry(QtCore.QRect(160, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.label_43 = QtWidgets.QLabel(self.centralwidget)
        self.label_43.setGeometry(QtCore.QRect(160, 310, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.centralwidget)
        self.label_44.setGeometry(QtCore.QRect(160, 460, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.centralwidget)
        self.label_45.setGeometry(QtCore.QRect(160, 410, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_46 = QtWidgets.QLabel(self.centralwidget)
        self.label_46.setGeometry(QtCore.QRect(600, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.centralwidget)
        self.label_47.setGeometry(QtCore.QRect(600, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_50 = QtWidgets.QLabel(self.centralwidget)
        self.label_50.setGeometry(QtCore.QRect(600, 360, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.centralwidget)
        self.label_51.setGeometry(QtCore.QRect(600, 460, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_54 = QtWidgets.QLabel(self.centralwidget)
        self.label_54.setGeometry(QtCore.QRect(850, 160, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.centralwidget)
        self.label_55.setGeometry(QtCore.QRect(850, 260, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setGeometry(QtCore.QRect(870, 100, 20, 491))
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_60 = QtWidgets.QLabel(self.centralwidget)
        self.label_60.setGeometry(QtCore.QRect(850, 210, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.centralwidget)
        self.label_61.setGeometry(QtCore.QRect(850, 110, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.centralwidget)
        self.label_62.setGeometry(QtCore.QRect(600, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.centralwidget)
        self.label_63.setGeometry(QtCore.QRect(850, 60, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.label_56 = QtWidgets.QLabel(self.centralwidget)
        self.label_56.setGeometry(QtCore.QRect(1120, 510, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.plot = QtWidgets.QPushButton(self.centralwidget)
        self.plot.setGeometry(QtCore.QRect(960, 585, 93, 28))
        self.plot.setObjectName("plot")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 26))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.browse = QtWidgets.QAction(MainWindow)
        self.browse.setObjectName("browse")
        self.menuFile.addAction(self.browse)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Sn, self.Sb)
        MainWindow.setTabOrder(self.Sb, self.Ub)
        MainWindow.setTabOrder(self.Ub, self.Xd)
        MainWindow.setTabOrder(self.Xd, self.Xq)
        MainWindow.setTabOrder(self.Xq, self.Xd1)
        MainWindow.setTabOrder(self.Xd1, self.Xq1)
        MainWindow.setTabOrder(self.Xq1, self.Xd2)
        MainWindow.setTabOrder(self.Xd2, self.Xq2)
        MainWindow.setTabOrder(self.Xq2, self.S2)
        MainWindow.setTabOrder(self.S2, self.Ug)
        MainWindow.setTabOrder(self.Ug, self.Zb)
        MainWindow.setTabOrder(self.Zb, self.Ib)
        MainWindow.setTabOrder(self.Ib, self.S2pu)
        MainWindow.setTabOrder(self.S2pu, self.Ugpu)
        MainWindow.setTabOrder(self.Ugpu, self.Igpu)
        MainWindow.setTabOrder(self.Igpu, self.deltaIgpu)
        MainWindow.setTabOrder(self.deltaIgpu, self.EQ)
        MainWindow.setTabOrder(self.EQ, self.phi)
        MainWindow.setTabOrder(self.phi, self.BC)
        MainWindow.setTabOrder(self.BC, self.OA)
        MainWindow.setTabOrder(self.OA, self.AB)
        MainWindow.setTabOrder(self.AB, self.alfa)
        MainWindow.setTabOrder(self.alfa, self.gamma)
        MainWindow.setTabOrder(self.gamma, self.Iqpu)
        MainWindow.setTabOrder(self.Iqpu, self.Idpu)
        MainWindow.setTabOrder(self.Idpu, self.Uqpu)
        MainWindow.setTabOrder(self.Uqpu, self.Udpu)
        MainWindow.setTabOrder(self.Udpu, self.Edpu2)
        MainWindow.setTabOrder(self.Edpu2, self.Eqpu2)
        MainWindow.setTabOrder(self.Eqpu2, self.Edpu1)
        MainWindow.setTabOrder(self.Edpu1, self.Eqpu1)
        MainWindow.setTabOrder(self.Eqpu1, self.Edpu)
        MainWindow.setTabOrder(self.Edpu, self.Eqpu)
        MainWindow.setTabOrder(self.Eqpu, self.Epu)
        MainWindow.setTabOrder(self.Epu, self.Epu1)
        MainWindow.setTabOrder(self.Epu1, self.Epu2)
        MainWindow.setTabOrder(self.Epu2, self.delta)
        MainWindow.setTabOrder(self.delta, self.comboSn)
        MainWindow.setTabOrder(self.comboSn, self.comboSb)
        MainWindow.setTabOrder(self.comboSb, self.comboUb)
        MainWindow.setTabOrder(self.comboUb, self.comboS2)
        MainWindow.setTabOrder(self.comboS2, self.calculate)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("State Visualizer of Synchronous Generator", "State Visualizer of Synchronous Generator"))
        self.label.setText(_translate("MainWindow", "Input Data"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">N</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">b</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">b</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">d</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">d&quot;</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">q</span></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">d\'</span></p></body></html>"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">q\'</span></p></body></html>"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p>X<span style=\" vertical-align:sub;\">q&quot;</span></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">2</span></p></body></html>"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p>Z<span style=\" vertical-align:sub;\">b</span></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "<html><head/><body><p>I<span style=\" vertical-align:sub;\">b</span></p></body></html>"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.comboUb.setItemText(0, _translate("MainWindow", "V"))
        self.comboUb.setItemText(1, _translate("MainWindow", "KV"))
        self.comboUb.setItemText(2, _translate("MainWindow", "MV"))
        self.comboSb.setItemText(0, _translate("MainWindow", "VA"))
        self.comboSb.setItemText(1, _translate("MainWindow", "KVA"))
        self.comboSb.setItemText(2, _translate("MainWindow", "MVA"))
        self.comboSb.setItemText(3, _translate("MainWindow", "GVA"))
        self.comboSn.setItemText(0, _translate("MainWindow", "VA"))
        self.comboSn.setItemText(1, _translate("MainWindow", "KVA"))
        self.comboSn.setItemText(2, _translate("MainWindow", "MVA"))
        self.comboSn.setItemText(3, _translate("MainWindow", "GVA"))
        self.comboS2.setItemText(0, _translate("MainWindow", "VA"))
        self.comboS2.setItemText(1, _translate("MainWindow", "KVA"))
        self.comboS2.setItemText(2, _translate("MainWindow", "MVA"))
        self.comboS2.setItemText(3, _translate("MainWindow", "GVA"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>I<span style=\" vertical-align:sub;\">gpu</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p>EQ</p></body></html>"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">𝛿</span><span style=\" vertical-align:sub;\">𝐼𝑔𝑝𝑢</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p>S<span style=\" vertical-align:sub;\">2pu</span></p><p><br/></p></body></html>"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">𝜑</span></p></body></html>"))
        self.label_22.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">gpu</span></p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">g</span></p><p><br/></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p>BC</p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p>AB</p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p>OA</p></body></html>"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">𝛼 </span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">𝛾</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p>I<span style=\" vertical-align:sub;\">qpu</span></p></body></html>"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p>I<span style=\" vertical-align:sub;\">dpu</span></p></body></html>"))
        self.label_31.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">qpu</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p>U<span style=\" vertical-align:sub;\">dpu</span></p></body></html>"))
        self.label_33.setText(_translate("MainWindow", "<html><head/><body><p>E&quot;<span style=\" vertical-align:sub;\">dpu</span></p></body></html>"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p>E&quot;<span style=\" vertical-align:sub;\">qpu</span></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p>E\'<span style=\" vertical-align:sub;\">qpu</span></p></body></html>"))
        self.label_36.setText(_translate("MainWindow", "<html><head/><body><p>E\'<span style=\" vertical-align:sub;\">dpu</span></p></body></html>"))
        self.label_37.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" vertical-align:sub;\">qpu</span></p></body></html>"))
        self.label_38.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" vertical-align:sub;\">dpu</span></p></body></html>"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p>E&quot;<span style=\" vertical-align:sub;\">pu</span></p></body></html>"))
        self.label_40.setText(_translate("MainWindow", "<html><head/><body><p>E\'<span style=\" vertical-align:sub;\">pu</span></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "<html><head/><body><p>E<span style=\" vertical-align:sub;\">pu</span></p></body></html>"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt;\">𝛿</span></p></body></html>"))
        self.help.setToolTip(_translate("MainWindow", "Help"))
        self.help.setText(_translate("MainWindow", "Help"))
        self.save.setText(_translate("MainWindow", "Save to a file"))
        self.label_13.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_43.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_44.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_46.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">A</span></p></body></html>"))
        self.label_47.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">Ω</span></p></body></html>"))
        self.label_50.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'serif\'; color:#222222; background-color:transparent;\">° </span></p></body></html>"))
        self.label_51.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'serif\'; color:#222222; background-color:transparent;\">°</span></p></body></html>"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">V</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'serif\'; color:#222222; background-color:transparent;\">°</span></p></body></html>"))
        self.label_60.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'serif\'; color:#222222; background-color:transparent;\">°</span></p></body></html>"))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">V</span></p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p>V</p></body></html>"))
        self.label_63.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'sans-serif\'; color:#000000; background-color:transparent;\">V</span></p></body></html>"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-family:\'serif\'; color:#222222; background-color:transparent;\">°</span></p></body></html>"))
        self.plot.setText(_translate("MainWindow", "Plot"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.browse.setText(_translate("MainWindow", "Import data from file"))


